[package]
authors = ["Xuanwo <github@xuanwo.io>"]
description = "Retry futures in backoff without effort."
documentation = "https://docs.rs/backon"
edition = "2021"
license = "Apache-2.0"
name = "backon"
version = "0.3.0"

[dependencies]
futures = "0.3"
pin-project = "1"
rand = "0.8"
tokio = { version = "1", features = ["time"] }

[dev-dependencies]
anyhow = "1"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
